PresentationLayer/Models/ErrorViewModel.cs
namespace PresentationLayer.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PresentationLayer/Controllers/BirimController.cs
using BusinessLayer.Abstract;
using EntityLayer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PresentationLayer.Models;

namespace PresentationLayer.Controllers
{
    public class BirimController : Controller
    {
        private readonly IBirimService _birimService;

        public BirimController(IBirimService birimService)
        {
            _birimService = birimService;
        }
      
        public IActionResult Index()
        {   var model = _birimService.GetAll();
            return View(model);
        }
        [HttpGet]
        public IActionResult BirimEkle()
        {
            return View();
        }
        [HttpPost]
        public IActionResult BirimEkle(Birim birim)
        {
            if (birim != null)
            {
                _birimService.Add(birim);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult BirimGuncelle(int id)
        {
            var birim = _birimService.GetBirimById(id);
            return View(birim);
        }
        [HttpPost]
        public IActionResult BirimGuncelle(Birim birim)
        {
            _birimService.Update(birim);
            return RedirectToAction("Index");
        }

        public ActionResult BirimSil(int id)
        {
            var birim = _birimService.GetBirimById(id);
            _birimService.Delete(birim);


            return RedirectToAction("Index"); ;
        }
    }
}

PresentationLayer/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PresentationLayer.Models;
using System.Diagnostics;

namespace PresentationLayer.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PresentationLayer/Controllers/LoginController.cs
using BusinessLayer.Abstract;
using EntityLayer;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace PresentationLayer.Controllers
{
    [AllowAnonymous]
    public class LoginController : Controller
    {
        private readonly IAdminService _adminService;
        public LoginController(IAdminService adminService)
        {
            _adminService = adminService;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Index(Admin admin)
        {
            var user = _adminService.AuthAdmin(admin);
            if (user != null)
            {
                var claims = new List<Claim>
                {
                     new Claim(ClaimTypes.Name, admin.KullaniciAdi)
                };
                var useridentity = new ClaimsIdentity(claims, "Login");
                ClaimsPrincipal principal = new ClaimsPrincipal(useridentity);
                await HttpContext.SignInAsync(principal);
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Login");
        }

    }
}

PresentationLayer/Controllers/PersonelController.cs
using BusinessLayer.Abstract;
using EntityLayer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace PresentationLayer.Controllers
{
    public class PersonelController : Controller
    {
        private readonly IPersonelService _personelService;
        private readonly IBirimService _birimService;
        public PersonelController(IPersonelService personelService, IBirimService birimService)
        {
            _personelService = personelService;
            _birimService = birimService;
        }
        [HttpGet]
        public IActionResult Index(int? id)
        {
            var liste = (List<Personel>)null;
            if (id == null)
                liste = _personelService.GetAll();
            else
                liste = _personelService.GetAllByBirim((int)id);
            return View(liste);
        }


        [HttpGet]
        public IActionResult PersonelEkle()
        {
            List<SelectListItem> birimListesi = (from x in _birimService.GetAll()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.BirimAd,
                                                     Value = x.Id.ToString()
                                                 }).ToList();
            ViewBag.bl = birimListesi;
            return View();
        }
        [HttpPost]
        public IActionResult PersonelEkle(Personel personel)
        {
            if (personel != null)
            {
                personel.Birim = _birimService.GetBirimById((int)personel.BirimId);
                _personelService.Add(personel);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult PersonelGuncelle(int id)
        {
            List<SelectListItem> birimListesi = (from x in _birimService.GetAll()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.BirimAd,
                                                     Value = x.Id.ToString()
                                                 }).ToList();
            ViewBag.bl = birimListesi;
            var personel = _personelService.GetPersonelById(id);
            return View(personel);
        }
        [HttpPost]
        public IActionResult PersonelGuncelle(Personel personel)
        {
            _personelService.Update(personel);
            return RedirectToAction("Index");
        }

        public IActionResult PersonelSil(int id)
        {
            var personel = _personelService.GetPersonelById(id);
            _personelService.Delete(personel);
            return RedirectToAction("Index");
        }
    }
}

PresentationLayer/Views/Birim/BirimEkle.cshtml
@model EntityLayer.Birim
@{
    ViewData["Title"] = "BirimEkle";
}

<h1>BirimEkle</h1>

@using (Html.BeginForm("BirimEkle", "Birim", FormMethod.Post)) 
{
<div class="form-group">
    @Html.Label("Birim Adı")
    @Html.TextBoxFor(x=>x.BirimAd, new { @class = "form-control" })
    <br />
    <br />
    <br />
    <button class="btn btn-info">Kaydet</button>


</div>    
}

PresentationLayer/Views/Birim/BirimGuncelle.cshtml
@model EntityLayer.Birim
@{
    ViewData["Title"] = "BirimGuncelle";
}

<h1>BirimGuncelle</h1>

@using (Html.BeginForm("BirimGuncelle", "Birim", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Birim Id")
        @Html.TextBoxFor(x => x.Id, new { @class = "form-control", @readonly = "readonly", @Name = "" })
        <br />
        @Html.Label("Birim Adı")
        @Html.TextBoxFor(x => x.BirimAd, new { @class = "form-control" })
        <br />
        <br />
        <button class="btn btn-success">Güncelle</button>

    </div>
}

PresentationLayer/Views/Birim/Index.cshtml
@using EntityLayer;
@model List<Birim>
@{
    ViewData["Title"] = "Index";
}



<table class="table table-bordered" style="margin-top:20px">
    <tr>
        <th>Birim</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Personeller</th>
    </tr>
@foreach (var item in Model)
{
<tr>
    <td>@item.BirimAd</td>
    <td><a href="/Birim/BirimSil/@item.Id" class="btn btn-danger">Sil</a></td>
    <td><a href="/Birim/BirimGuncelle/@item.Id" class="btn btn-warning">Güncelle</a></td>
    <td><a href="/Personel/Index/@item.Id" class="btn btn-warning">Personeller</a></td>

</tr>
}

</table>
<a href="/Birim/BirimEkle" class="btn btn-info">Yeni Birim Ekle</a>

PresentationLayer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PresentationLayer/Views/Login/Index.cshtml
@model EntityLayer.Admin;
@{
    Layout = null;
}

<!DOCTYPE html>


<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Bootstrap Simple Login Form</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
<style>
	.login-form {
		width: 340px;
    	margin: 50px auto;
	}
    .login-form form {
    	margin-bottom: 15px;
        background: #f7f7f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
    .login-form h2 {
        margin: 0 0 15px;
    }
    .form-control, .btn {
        min-height: 38px;
        border-radius: 2px;
    }
    .btn {        
        font-size: 15px;
        font-weight: bold;
    }
</style>
</head>
<body>
<div class="login-form">
    <form action="~/Login/Index" method="post">
        <h2 class="text-center">Admin Girişi</h2>       
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Kullanıcı Adı" name="KullaniciAdi" required="required">
        </div>
        <div class="form-group">
            <input type="password" class="form-control" placeholder="Şifre" name="Sifre" required="required">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Giriş</button>
        </div>
                
    </form>
</div>
</body>
</html>                                		

PresentationLayer/Views/Personel/Index.cshtml
@using EntityLayer
@model List<Personel>
@{
    ViewData["Title"] = "Index";
}

<h1>Personel Listesi </h1>
<br />
<table class="table table-bordered" style="margin-top:20px">
    <tr>
        <th>Personel</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
@foreach (var item in Model)
{
<tr>
    <td>@item.Ad @item.Soyad</td>
    <td><a href="/Personel/PersonelSil/@item.Id" class="btn btn-danger">Sil</a></td>
    <td><a href="/Personel/PersonelGuncelle/@item.Id" class="btn btn-warning">Güncelle</a></td>

</tr>
}

</table>
<a href="/Personel/PersonelEkle" class="btn btn-info">Yeni Personel Ekle</a>

PresentationLayer/Views/Personel/PersonelEkle.cshtml
@model EntityLayer.Personel
@{
    ViewData["Title"] = "PersonelEkle";
}

<h1>PersonelEkle</h1>

@using (Html.BeginForm("PersonelEkle", "Personel", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Ad")
        @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
        <br />
        @Html.Label("Soyad")
        @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control" })
        <br />

        @Html.Label("Birim")
        @Html.DropDownListFor(x => x.BirimId,(List<SelectListItem>)ViewBag.bl, new { @class = "form-control" })
        <br />
        <br />
        <br />
        <button class="btn btn-info">Kaydet</button>
    </div>
}

PresentationLayer/Views/Personel/PersonelGuncelle.cshtml
@model EntityLayer.Personel
@{
    ViewData["Title"] = "PersonelGuncelle";
}

<h1>PersonelGuncelle</h1>

@using (Html.BeginForm("PersonelGuncelle", "Personel", FormMethod.Post)) 
{ 
    <div class="form-group">
        @Html.Label("Birim Id")
        @Html.TextBoxFor(x => x.Id, new  {@class="form-control",  @readonly = "readonly", @Name = "" })
        <br />
        @Html.Label("Birim Adı")
        @Html.TextBoxFor(x=>x.Ad, new { @class = "form-control" })
        <br />
        @Html.Label("Birim Adı")
        @Html.TextBoxFor(x=>x.Soyad, new { @class = "form-control" })
        <br />
        @Html.Label("Birim")
        @Html.DropDownListFor(x => x.BirimId,(List<SelectListItem>)ViewBag.bl, new { @class = "form-control" })

<br />
        <button class="btn btn-success">Güncelle</button>

    </div>
}

PresentationLayer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Örnek Proje</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PresentationLayer.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Örnek Proje</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Birim" asp-action="Index">Birim Listesi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personel" asp-action="Index">Personel Listesi</a>
                        </li>
                         <li class="nav-item">
                            <a href="/Login/LogOut" class="nav-link text-dark">Çıkış</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Örnek Proje - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>